const getters = {
  //user
  token: state => state.user.token,
  userId: state => state.user.userId,
  activeUserId: state => state.user.activeUserId,
  userInfo: state => state.user.userInfo,
  userOrderList: state => state.user.userOrderList,
  userClientList: state => state.user.userClientList,
  userHotelList: state => state.user.userHotelList,
  userOrderId: state => state.user.userOrderId,
  userOrderDetail: state => state.user.userOrderDetail,
  orderVisible: state => state.user.orderVisible,
  //addClientModalVisible: state => state.user.addClientModalVisible,

  hotelListLoading: state => state.hotel.hotelListLoading,
  hotelList: state => state.hotel.hotelList,
  displayHotelList: state => state.hotel.displayHotelList,
    isSearching: state => state.hotel.isSearching,
    isTableDisplay: state => state.hotel.isTableDisplay,
    currentHotelInfo: state => state.hotel.currentHotelInfo,
  currentHotelId: state => state.hotel.currentHotelId,
  orderModalVisible: state => state.hotel.orderModalVisible,
  currentOrderRoom: state => state.hotel.currentOrderRoom,
  orderMatchCouponList: state => state.hotel.orderMatchCouponList,
  //admin
  managerList: state => state.admin.managerList,
  clientList: state => state.admin.clientList,
  addManagerModalVisible: state => state.admin.addManagerModalVisible,
  showHotelModalVisible: state => state.admin.showHotelModalVisible,
  addHotelManageModalVisible: state=>state.admin.addHotelManageModalVisible,
  addClientModalVisible: state=>state.admin.addClientModalVisible,
  currentManagerId: state=>state.admin.currentManagerId,
  addManagerParams: state => state.admin.addManagerParams,
  addHotelManageParams: state => state.admin.addHotelManageParams,
  manageAddHotelModalVisible: state => state.admin.manageAddHotelModalVisible,
  //hotelManager
  managerHotelList: state => state.hotelManager.managerHotelList,
  orderList: state => state.hotelManager.orderList,
  addHotelModalVisible: state => state.hotelManager.addHotelModalVisible,
  addRoomModalVisible: state => state.hotelManager.addRoomModalVisible,
  couponVisible: state => state.hotelManager.couponVisible,
  addCouponVisible: state => state.hotelManager.addCouponVisible,
  changeRoomVisible:state=> state.hotelManager.changeRoomVisible,
  dealRoomChangeModalVisible:state=> state.hotelManager.dealRoomChangeModalVisible,
  changeRoomId:state=> state.hotelManager.changeRoomId,
  activeHotelId: state => state.hotelManager.activeHotelId,
  activeRoomId: state => state.hotelManager.activeRoomId,
  couponList: state => state.hotelManager.couponList,
  updateHotelInfoModalVisible:state=> state.hotelManager.updateHotelInfoModalVisible,
  //remark
  remarkList: state => state.hotel.remarkList,
  ableToRemark: state => state.hotel.ableToRemark,
  addRemarkModalVisible: state => state.hotel.addRemarkModalVisible,
  managerOrderVisible: state => state.hotelManager.managerOrderVisible,
  activeOrderId: state => state.hotelManager.activeOrderId,
  activeOrderDetail: state => state.hotelManager.activeOrderDetail,
  }
  
  export default getters